使用本地base node代码

diff --git a/reth/Dockerfile b/reth/Dockerfile
--- a/reth/Dockerfile
+++ b/reth/Dockerfile
@@ -13,21 +13,21 @@ RUN . /tmp/versions.env && git clone $OP_NODE_REPO --branch $OP_NODE_TAG --singl
 RUN . /tmp/versions.env && cd op-node && \
     make VERSION=$OP_NODE_TAG op-node
 
-FROM rust:1.88 AS reth-base
+# FROM rust:1.88 AS reth-base
 
-WORKDIR /app
+# WORKDIR /app
 
-COPY versions.env /tmp/versions.env
+# COPY versions.env /tmp/versions.env
 
-RUN apt-get update && apt-get -y upgrade && \
-    apt-get install -y git libclang-dev pkg-config curl build-essential && \
-    rm -rf /var/lib/apt/lists/*
+# RUN apt-get update && apt-get -y upgrade && \
+#     apt-get install -y git libclang-dev pkg-config curl build-essential && \
+#     rm -rf /var/lib/apt/lists/*
 
-RUN . /tmp/versions.env && git clone $BASE_RETH_NODE_REPO . && \
-    git checkout tags/$BASE_RETH_NODE_TAG && \
-    bash -c '[ "$(git rev-parse HEAD)" = "$BASE_RETH_NODE_COMMIT" ]' || (echo "Commit hash verification failed" && exit 1)
+# RUN . /tmp/versions.env && git clone $BASE_RETH_NODE_REPO . && \
+#     git checkout tags/$BASE_RETH_NODE_TAG && \
+#     bash -c '[ "$(git rev-parse HEAD)" = "$BASE_RETH_NODE_COMMIT" ]' || (echo "Commit hash verification failed" && exit 1)
 
-RUN cargo build --bin base-reth-node --profile maxperf
+# RUN cargo build --bin base-reth-node --profile maxperf
 
 FROM ubuntu:24.04
 
@@ -39,7 +39,7 @@ RUN mkdir -p /var/log/supervisor
 WORKDIR /app
 
 COPY --from=op /app/op-node/bin/op-node ./
-COPY --from=reth-base /app/target/maxperf/base-reth-node ./
+COPY ../base-node/target/maxperf/base-reth-node ./
 COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
 COPY ./reth/reth-entrypoint ./execution-entrypoint
 COPY op-node-entrypoint .
